### ISSUE TITLE
Setup script is not working on Mac

### ISSUE THREAD

**Issue by pditommaso** [mirnylab/distiller-nf#17]
Just reporting in the case you are interested to have it working in Mac OS

```bash
$ bash setup_test.sh 
++ pwd
+ PROJECT_DIR=/Users/pditommaso/Downloads/test/test
+ mkdir -p /Users/pditommaso/Downloads/test/test
+ cd /Users/pditommaso/Downloads/test/test
+ curl -LkSs https://api.github.com/repos/mirnylab/distiller-test-data/tarball
+ tar -zxf - --strip=1 --wildcards '*/genome/*' --wildcards '*/fastq/*'
tar: Option --wildcards is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
curl: (23) Failed writing body (0 != 1370)
```

**Comment by golobor** [comment]
hi! I rewrote the test_setup script with an intention of using only cross-platform command line tools. Would you be willing to try it out on your system?
I also looked into adding OS X continuous integration, but it turned out that travis at the moment cannot launch docker containers inside OS X testing environment. :(

**Comment by pditommaso** [comment]
Setup script worked smoothly

**Comment by golobor** [comment]
thank you for testing!!
