### ISSUE TITLE
Missing parallel tool

### ISSUE THREAD

**Issue by pditommaso** [mirnylab/distiller-nf#23]
I think `parallel` should be installed in the container.  I'm getting this error 

```
ERROR ~ Error executing process > 'parse_runs (library:MATa_R2 run:lane1)'

Caused by:
  Process `parse_runs (library:MATa_R2 run:lane1)` terminated with an error exit status (127)

Command executed:

  mkdir ./tmp4sort
  mkdir ./tmp_pairsam
  parallel -P4 'pairsamtools parse                {}             | pairsamtools sort --nproc 4                                 -o ./tmp_pairsam/{}.pairsam.gz                                 --tmpdir ./tmp4sort ' ::: MATa_R2.lane1.00.bam MATa_R2.lane1.01.bam
  
  pairsamtools merge ./tmp_pairsam/* --nproc 8 -o MATa_R2.lane1.pairsam.gz
  
  rm -rf ./tmp4sort
  rm -rf ./tmp_pairsam
  
  pairsamtools stats MATa_R2.lane1.pairsam.gz -o MATa_R2.lane1.stats

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 4: parallel: command not found
  .command.run.1: line 104:    13 Terminated              nxf_trace "$pid" .command.trace

```

**Comment by golobor** [comment]
Hi, Paolo,
I believe that the issue was b/c I updated the docker without bumping the version, such that docker did not notice an update of the container and did not pull it. This also caused travis not noticing the issue - it pulls the container on every test.
I have bumped the version of distiler and its container, which must trigger a pull now.
Please, let me know if it works! Sorry for the clunkiness - I am still trying to figure out the best way to version such a rapidly updated tool.
Thank you for your feedback,
Anton.

**Comment by pditommaso** [comment]
Yes, that was the problem. All right now.
