### ISSUE TITLE
Delete .sra after finished chunking 

### ISSUE THREAD

**Issue by mimakaev** [mirnylab/distiller-nf#29]
Currently they are somewhere in the work folder, I believe

**Comment by sergpolly** [comment]
that's by design of `nextflow`; `work` stores the results of all `processes` in isolated folders, and downstream `processes`  can access these results only by the means of nextflow `channels` and cannot delete them.

**Comment by golobor** [comment]
Max's point can be expanded: we can delete .sras at the end of the download_sra process, which is definitely something to discuss.

Currently, there are two ways to download .sra:
1) when we use a whole sra, we wget it and then fastq-dump it.
https://github.com/mirnylab/distiller-nf/blob/4f27a984cea7113f66f291ad2f093fc22711886a/distiller.nf#L91

In this scenario, we probably should delete .sra, since they can't be re-used upon -resume.

2) When we map only a fraction of .sra, we download that fraction via fastq-dump.

https://github.com/mirnylab/distiller-nf/blob/4f27a984cea7113f66f291ad2f093fc22711886a/distiller.nf#L84

In this scenario, we do not explicitly store .sra in the work folder. BUT fastq-dump caches this chunk in it own user-wide cache (!). This is probably an unwanted behavior, but we can't disable it easily with a CLI flag.

To conclude, we could add a line:
rm ${srr}.sra 
to
https://github.com/mirnylab/distiller-nf/blob/4f27a984cea7113f66f291ad2f093fc22711886a/distiller.nf#L95

**Comment by golobor** [comment]
solved when downloading both using fastq-dump and wget (in these two scenarios, .sras get stored in different locations)
