### ISSUE TITLE
option to balance coolers? 

### ISSUE THREAD

**Issue by mimakaev** [mirnylab/distiller-nf#45]
Could be nice way to avoid needing to re-balance everything after mapping

**Comment by mimakaev** [comment]
bump

**Comment by sergpolly** [comment]
We'd need to balance both `library` coolers and `library_group` coolers, right? As far as I know `cooler merge` won't merge balance vectors or re-balance stuff.

We could simply introduce `${balance_command} = "cooler balance etc" if params.balance_flag else ""` in the binning process and when merging coolers into library groups:
here:

https://github.com/mirnylab/distiller-nf/blob/09a9b41567587384ccb39c76da49f7986f381789/distiller.nf#L580

and here:

https://github.com/mirnylab/distiller-nf/blob/09a9b41567587384ccb39c76da49f7986f381789/distiller.nf#L616

So that way we'll have a single flag to control balancing on library and library_group level.
If that sounds ok/appropriate, I could do this

**Comment by sergpolly** [comment]
@golobor @nvictus please comment on this and #65 , so that we would implement something that makes the most sense

**Comment by golobor** [comment]
resolved by @sergpolly
